# Generated by Django 5.2.11 on 2026-02-14 05:05

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_image"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du modèle"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("worship", "Culte"),
                            ("group", "Réunion de groupe"),
                            ("meal", "Repas communautaire"),
                            ("special", "Événement spécial"),
                            ("meeting", "Réunion"),
                            ("training", "Formation"),
                            ("outreach", "Évangélisation"),
                            ("other", "Autre"),
                        ],
                        default="worship",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "default_duration",
                    models.DurationField(
                        blank=True,
                        help_text="Format: HH:MM:SS",
                        null=True,
                        verbose_name="Durée par défaut",
                    ),
                ),
                (
                    "default_description",
                    models.TextField(blank=True, verbose_name="Description par défaut"),
                ),
                (
                    "default_capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Capacité par défaut"
                    ),
                ),
                (
                    "default_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Lieu par défaut",
                    ),
                ),
                (
                    "requires_rsvp",
                    models.BooleanField(
                        default=False, verbose_name="RSVP requis par défaut"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle d'événement",
                "verbose_name_plural": "Modèles d'événements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=0, verbose_name="Capacité"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "amenities_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste JSON des équipements disponibles",
                        verbose_name="Équipements",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="rooms/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salle",
                "verbose_name_plural": "Salles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="campus",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Campus"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_hybrid",
            field=models.BooleanField(
                default=False,
                help_text="En personne et en ligne",
                verbose_name="Événement hybride",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="kiosk_mode_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Mode kiosque activé"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin de récurrence"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Quotidien"),
                    ("weekly", "Hebdomadaire"),
                    ("biweekly", "Aux deux semaines"),
                    ("monthly", "Mensuel"),
                    ("yearly", "Annuel"),
                ],
                default="",
                max_length=20,
                verbose_name="Fréquence de récurrence",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_rule",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Format RRULE iCal (optionnel, surcharge fréquence)",
                max_length=255,
                verbose_name="Règle de récurrence",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="virtual_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zoom", "Zoom"),
                    ("google_meet", "Google Meet"),
                    ("teams", "Microsoft Teams"),
                    ("youtube", "YouTube Live"),
                    ("facebook", "Facebook Live"),
                    ("other", "Autre"),
                ],
                default="",
                max_length=20,
                verbose_name="Plateforme virtuelle",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="virtual_url",
            field=models.URLField(
                blank=True, default="", verbose_name="URL de la réunion virtuelle"
            ),
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="events/photos/%Y/%m/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="Image",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Légende"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approuvé"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_event_photos",
                        to="members.member",
                        verbose_name="Téléversé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo d'événement",
                "verbose_name_plural": "Photos d'événements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "questions_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste JSON: [{question, type, options, required}]",
                        verbose_name="Questions",
                    ),
                ),
                (
                    "send_after_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Envoyer X heures après l'événement"
                    ),
                ),
                (
                    "survey_sent",
                    models.BooleanField(default=False, verbose_name="Sondage envoyé"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sondage",
                "verbose_name_plural": "Sondages",
            },
        ),
        migrations.CreateModel(
            name="EventVolunteerNeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "position_name",
                    models.CharField(max_length=200, verbose_name="Nom du poste"),
                ),
                (
                    "required_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre requis"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_needs",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Besoin de bénévole",
                "verbose_name_plural": "Besoins de bénévoles",
            },
        ),
        migrations.CreateModel(
            name="RegistrationForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Titre du formulaire",
                    ),
                ),
                (
                    "fields_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste JSON des champs: [{name, type, label, required, options}]",
                        verbose_name="Champs du formulaire",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_forms",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulaire d'inscription",
                "verbose_name_plural": "Formulaires d'inscription",
            },
        ),
        migrations.CreateModel(
            name="RoomBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="Début")),
                ("end_datetime", models.DateTimeField(verbose_name="Fin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("cancelled", "Annulée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_bookings",
                        to="members.member",
                        verbose_name="Réservé par",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_bookings",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="events.room",
                        verbose_name="Salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation de salle",
                "verbose_name_plural": "Réservations de salles",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EventVolunteerSignup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_volunteer_signups",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="events.eventvolunteerneed",
                        verbose_name="Besoin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription bénévole",
                "verbose_name_plural": "Inscriptions bénévoles",
                "unique_together": {("need", "member")},
            },
        ),
        migrations.CreateModel(
            name="EventWaitlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ajouté le"),
                ),
                (
                    "promoted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Promu le"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_waitlists",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste d'attente",
                "verbose_name_plural": "Listes d'attente",
                "ordering": ["position"],
                "unique_together": {("event", "member")},
            },
        ),
        migrations.CreateModel(
            name="RegistrationEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "data_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Données soumises"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Soumis le"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_entries",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="events.registrationform",
                        verbose_name="Formulaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "unique_together": {("form", "member")},
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "answers_json",
                    models.JSONField(blank=True, default=dict, verbose_name="Réponses"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Soumis le"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="events.eventsurvey",
                        verbose_name="Sondage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse au sondage",
                "verbose_name_plural": "Réponses aux sondages",
                "unique_together": {("survey", "member")},
            },
        ),
    ]
