# Generated by Django 5.2.11 on 2026-02-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_admin_reviewed_at_member_admin_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="two_factor_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date limite activation 2FA"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA activé"),
        ),
    ]
