# Generated by Django 5.2.11 on 2026-02-06 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_alter_event_image"),
        ("members", "0002_member_admin_reviewed_at_member_admin_reviewed_by_and_more"),
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "consecutive_absences",
                    models.PositiveIntegerField(verbose_name="Absences consécutives"),
                ),
                (
                    "last_attendance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dernière présence"
                    ),
                ),
                (
                    "alert_sent",
                    models.BooleanField(default=False, verbose_name="Alerte envoyée"),
                ),
                (
                    "alert_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Alerte envoyée le"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to="members.member",
                        verbose_name="Reconnu par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_alerts",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte d'absence",
                "verbose_name_plural": "Alertes d'absence",
                "ordering": ["-consecutive_absences"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Culte du 15 mars 2025",
                        max_length=200,
                        verbose_name="Nom de la session",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("worship", "Culte"),
                            ("event", "Événement"),
                            ("lesson", "Leçon de formation"),
                            ("other", "Autre"),
                        ],
                        default="worship",
                        max_length=30,
                        verbose_name="Type de session",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de début"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True,
                        help_text="Le check-in est accepté",
                        verbose_name="Session ouverte",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions",
                        to="events.event",
                        verbose_name="Événement lié",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_sessions",
                        to="members.member",
                        verbose_name="Ouvert par",
                    ),
                ),
                (
                    "scheduled_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_session",
                        to="onboarding.scheduledlesson",
                        verbose_name="Leçon liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de présence",
                "verbose_name_plural": "Sessions de présence",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="MemberQRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Généré le"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/%Y/%m/",
                        verbose_name="Image QR",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code QR membre",
                "verbose_name_plural": "Codes QR membres",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Enregistré à"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("qr_scan", "Scan QR"), ("manual", "Manuel")],
                        default="qr_scan",
                        max_length=20,
                        verbose_name="Méthode",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scanned_records",
                        to="members.member",
                        verbose_name="Scanné par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.attendancesession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enregistrement de présence",
                "verbose_name_plural": "Enregistrements de présence",
                "ordering": ["-checked_in_at"],
                "unique_together": {("session", "member")},
            },
        ),
    ]
