# Generated by Django 5.2.11 on 2026-02-14 05:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancesession_duration_minutes"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoFence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Église principale",
                        max_length=200,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Rayon de la zone de check-in automatique",
                        verbose_name="Rayon (mètres)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone géographique",
                "verbose_name_plural": "Zones géographiques",
            },
        ),
        migrations.AddField(
            model_name="absencealert",
            name="acknowledged_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reconnu le"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="checked_out_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Heure de sortie (check-out)",
                null=True,
                verbose_name="Sorti à",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("qr_scan", "Scan QR"),
                    ("manual", "Manuel"),
                    ("nfc", "NFC/Tap"),
                    ("kiosk", "Kiosque"),
                    ("geo", "Géolocalisation"),
                ],
                default="qr_scan",
                max_length=20,
                verbose_name="Méthode",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Semaines consécutives avec présence",
                        verbose_name="Série actuelle",
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Plus longue série"
                    ),
                ),
                (
                    "last_attendance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dernière présence"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_streak",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Série de présence",
                "verbose_name_plural": "Séries de présence",
            },
        ),
        migrations.CreateModel(
            name="ChildCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Heure d'arrivée"
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de sortie"
                    ),
                ),
                (
                    "security_code",
                    models.CharField(
                        db_index=True,
                        help_text="Code à 6 chiffres pour le retrait sécurisé",
                        max_length=6,
                        unique=True,
                        verbose_name="Code de sécurité",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_checkouts",
                        to="members.member",
                        verbose_name="Retiré par",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="members.child",
                        verbose_name="Enfant",
                    ),
                ),
                (
                    "parent_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_checkins",
                        to="members.member",
                        verbose_name="Parent / tuteur",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_checkins",
                        to="attendance.attendancesession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enregistrement enfant",
                "verbose_name_plural": "Enregistrements enfants",
                "ordering": ["-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="KioskConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Kiosque entrée principale",
                        max_length=200,
                        verbose_name="Nom du kiosque",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Emplacement"
                    ),
                ),
                (
                    "admin_pin",
                    models.CharField(
                        help_text="Code PIN pour accéder à la configuration",
                        max_length=10,
                        verbose_name="PIN d'administration",
                    ),
                ),
                (
                    "auto_timeout_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Retour à l'écran d'accueil après inactivité",
                        verbose_name="Délai d'inactivité (secondes)",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kiosks",
                        to="attendance.attendancesession",
                        verbose_name="Session courante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration kiosque",
                "verbose_name_plural": "Configurations kiosques",
            },
        ),
        migrations.CreateModel(
            name="NFCTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "tag_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identifiant unique du tag NFC",
                        max_length=100,
                        unique=True,
                        verbose_name="Identifiant NFC",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Enregistré le"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nfc_tag",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag NFC",
                "verbose_name_plural": "Tags NFC",
            },
        ),
        migrations.CreateModel(
            name="VisitorInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom complet")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Courriel"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Visite spontanée"),
                            ("referral", "Référence"),
                            ("online", "En ligne"),
                            ("event", "Événement"),
                            ("other", "Autre"),
                        ],
                        default="walk_in",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "follow_up_completed",
                    models.BooleanField(default=False, verbose_name="Suivi complété"),
                ),
                (
                    "follow_up_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Suivi complété le"
                    ),
                ),
                (
                    "welcome_sent",
                    models.BooleanField(
                        default=False, verbose_name="Bienvenue envoyée"
                    ),
                ),
                (
                    "follow_up_assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_followups",
                        to="members.member",
                        verbose_name="Suivi assigné à",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitors",
                        to="attendance.attendancesession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visiteur",
                "verbose_name_plural": "Visiteurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
