# Generated by Django 5.2.11 on 2026-02-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_geofence_absencealert_acknowledged_at_and_more"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorinfo",
            name="follow_up_assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_visitor_followups",
                to="members.member",
                verbose_name="Suivi assigné à",
            ),
        ),
    ]
