# Generated by Django 5.0.6 on 2026-01-28 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('goal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant cible de la campagne', max_digits=12, verbose_name='Objectif')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/%Y/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Campagne de dons',
                'verbose_name_plural': 'Campagnes de dons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date à laquelle cet enregistrement a été supprimé', null=True, verbose_name='Date de suppression')),
                ('donation_number', models.CharField(editable=False, help_text='Généré automatiquement', max_length=20, unique=True, verbose_name='Numéro de don')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('donation_type', models.CharField(choices=[('tithe', 'Dîme'), ('offering', 'Offrande générale'), ('special', 'Offrande spéciale'), ('campaign', 'Campagne'), ('building', 'Bâtiment'), ('missions', 'Missions'), ('other', 'Autre')], default='offering', max_length=20, verbose_name='Type de don')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('check', 'Chèque'), ('card', 'Carte de crédit/débit'), ('bank_transfer', 'Virement bancaire'), ('online', 'En ligne'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du don')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque')),
                ('transaction_id', models.CharField(blank=True, help_text='Référence de la transaction en ligne', max_length=100, verbose_name='ID de transaction')),
                ('receipt_sent', models.BooleanField(default=False, verbose_name='Reçu envoyé')),
                ('receipt_sent_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi du reçu")),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='members.member', verbose_name='Membre')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Personne qui a enregistré le don (pour les dons en espèces)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_donations', to='members.member', verbose_name='Enregistré par')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donationcampaign', verbose_name='Campagne')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['donation_number'], name='donations_d_donatio_aaa256_idx'), models.Index(fields=['member', 'date'], name='donations_d_member__210aa4_idx'), models.Index(fields=['date'], name='donations_d_date_2e5b5c_idx'), models.Index(fields=['donation_type'], name='donations_d_donatio_5e5d0e_idx'), models.Index(fields=['payment_method'], name='donations_d_payment_ef61a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de reçu')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/', verbose_name='Fichier PDF')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Envoyé par courriel')),
                ('email_sent_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('member_name', models.CharField(help_text='Nom au moment de la génération', max_length=200, verbose_name='Nom du membre')),
                ('member_address', models.TextField(blank=True, help_text='Adresse au moment de la génération', verbose_name='Adresse du membre')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to='members.member', verbose_name='Généré par')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_receipts', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Reçu fiscal',
                'verbose_name_plural': 'Reçus fiscaux',
                'ordering': ['-year', '-generated_at'],
                'indexes': [models.Index(fields=['receipt_number'], name='donations_t_receipt_db7ee8_idx'), models.Index(fields=['member', 'year'], name='donations_t_member__651aa6_idx'), models.Index(fields=['year'], name='donations_t_year_366836_idx')],
                'unique_together': {('member', 'year')},
            },
        ),
    ]
