# Generated by Django 5.2.11 on 2026-02-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_donation_currency_cryptodonation_donationimport_and_more"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="givinggoal",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donation_giving_goals",
                to="members.member",
                verbose_name="Membre",
            ),
        ),
        migrations.AlterField(
            model_name="givingstatement",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donation_giving_statements",
                to="members.member",
                verbose_name="Membre",
            ),
        ),
    ]
