# Generated by Django 5.2.11 on 2026-02-14 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Utilisez {{member_name}}, {{event_title}}, etc.",
                        max_length=300,
                        verbose_name="Sujet du modèle",
                    ),
                ),
                (
                    "body_html_template",
                    models.TextField(
                        help_text="Contenu HTML du modèle avec variables de fusion.",
                        verbose_name="Corps HTML",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("welcome", "Bienvenue"),
                            ("event_reminder", "Rappel d'événement"),
                            ("birthday", "Anniversaire"),
                            ("giving_receipt", "Reçu de don"),
                            ("follow_up", "Suivi"),
                            ("general", "Général"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="Catégorie",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Modèle de courriel",
                "verbose_name_plural": "Modèles de courriel",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "body_template",
                    models.TextField(
                        help_text="Utilisez {{member_name}}, {{event_title}}, etc.",
                        verbose_name="Corps du modèle",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Modèle SMS",
                "verbose_name_plural": "Modèles SMS",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ABTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "variant_a_subject",
                    models.CharField(max_length=300, verbose_name="Sujet variante A"),
                ),
                (
                    "variant_b_subject",
                    models.CharField(max_length=300, verbose_name="Sujet variante B"),
                ),
                (
                    "variant_a_content",
                    models.TextField(blank=True, verbose_name="Contenu variante A"),
                ),
                (
                    "variant_b_content",
                    models.TextField(blank=True, verbose_name="Contenu variante B"),
                ),
                (
                    "test_size_pct",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Pourcentage d'audience pour chaque variante.",
                        verbose_name="Taille du test (%)",
                    ),
                ),
                (
                    "variant_a_opens",
                    models.PositiveIntegerField(default=0, verbose_name="Ouvertures A"),
                ),
                (
                    "variant_b_opens",
                    models.PositiveIntegerField(default=0, verbose_name="Ouvertures B"),
                ),
                (
                    "variant_a_clicks",
                    models.PositiveIntegerField(default=0, verbose_name="Clics A"),
                ),
                (
                    "variant_b_clicks",
                    models.PositiveIntegerField(default=0, verbose_name="Clics B"),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        help_text="A ou B",
                        max_length=1,
                        verbose_name="Gagnant",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("running", "En cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "newsletter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_test",
                        to="communication.newsletter",
                        verbose_name="Infolettre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test A/B",
                "verbose_name_plural": "Tests A/B",
            },
        ),
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("member_created", "Nouveau membre créé"),
                            ("first_visit", "Première visite"),
                            ("birthday", "Anniversaire"),
                            ("anniversary", "Anniversaire d'adhésion"),
                            ("donation_received", "Don reçu"),
                            ("event_rsvp", "Inscription événement"),
                            ("custom", "Personnalisé"),
                        ],
                        default="member_created",
                        max_length=30,
                        verbose_name="Déclencheur",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_automations",
                        to="members.member",
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automatisation",
                "verbose_name_plural": "Automatisations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("body", models.TextField(verbose_name="Message")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="members.member",
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="members.member",
                        verbose_name="Expéditeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message direct",
                "verbose_name_plural": "Messages directs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_group_chats",
                        to="members.member",
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_chats",
                        to="members.member",
                        verbose_name="Membres",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discussion de groupe",
                "verbose_name_plural": "Discussions de groupe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("body", models.TextField(verbose_name="Message")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Envoyé le"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.groupchat",
                        verbose_name="Discussion",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_chat_messages",
                        to="members.member",
                        verbose_name="Expéditeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de groupe",
                "verbose_name_plural": "Messages de groupe",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Numéro de téléphone"),
                ),
                ("body", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("sent", "Envoyé"),
                            ("delivered", "Livré"),
                            ("failed", "Échec"),
                            ("undelivered", "Non livré"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "twilio_sid",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Twilio SID"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Envoyé le"
                    ),
                ),
                (
                    "recipient_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_messages",
                        to="members.member",
                        verbose_name="Membre destinataire",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_sms",
                        to="members.member",
                        verbose_name="Envoyé par",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="communication.smstemplate",
                        verbose_name="Modèle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message SMS",
                "verbose_name_plural": "Messages SMS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Étape actuelle"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("paused", "En pause"),
                            ("completed", "Complété"),
                            ("cancelled", "Annulé"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Débuté le"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "next_step_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prochaine étape le"
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="communication.automation",
                        verbose_name="Automatisation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_enrollments",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription d'automatisation",
                "verbose_name_plural": "Inscriptions d'automatisation",
                "unique_together": {("automation", "member")},
            },
        ),
        migrations.CreateModel(
            name="AutomationStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "delay_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de jours à attendre avant d'envoyer ce message.",
                        verbose_name="Délai (jours)",
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Sujet")),
                ("body", models.TextField(verbose_name="Corps du message")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Courriel"),
                            ("sms", "SMS"),
                            ("push", "Notification push"),
                            ("in_app", "Notification in-app"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="communication.automation",
                        verbose_name="Automatisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape d'automatisation",
                "verbose_name_plural": "Étapes d'automatisation",
                "ordering": ["automation", "order"],
                "unique_together": {("automation", "order")},
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("endpoint", models.URLField(max_length=500, verbose_name="Endpoint")),
                (
                    "p256dh_key",
                    models.CharField(max_length=200, verbose_name="Clé P256DH"),
                ),
                ("auth_key", models.CharField(max_length=200, verbose_name="Clé Auth")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement push",
                "verbose_name_plural": "Abonnements push",
                "unique_together": {("member", "endpoint")},
            },
        ),
        migrations.CreateModel(
            name="SMSOptOut",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Numéro de téléphone"),
                ),
                (
                    "opted_out_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de désinscription"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_optouts",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Désinscription SMS",
                "verbose_name_plural": "Désinscriptions SMS",
                "unique_together": {("phone_number",)},
            },
        ),
    ]
