# Generated by Django 5.2.11 on 2026-02-07 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_alter_event_image"),
        ("members", "0005_default_departments"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibleMemberList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("prelude", "Prélude"),
                            ("annonces", "Annonces"),
                            ("louange", "Louange"),
                            ("offrande", "Offrande"),
                            ("predication", "Prédication"),
                            ("communion", "Sainte Cène"),
                            ("priere", "Prière"),
                            ("benediction", "Bénédiction"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Type de section",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eligible_lists",
                        to="members.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="eligible_for_sections",
                        to="members.member",
                        verbose_name="Membres éligibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste d'éligibilité",
                "verbose_name_plural": "Listes d'éligibilité",
            },
        ),
        migrations.CreateModel(
            name="WorshipService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("planned", "Planifié"),
                            ("confirmed", "Confirmé"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "theme",
                    models.CharField(blank=True, max_length=300, verbose_name="Thème"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "validation_deadline",
                    models.DateField(
                        blank=True,
                        help_text="14 jours avant le culte par défaut",
                        null=True,
                        verbose_name="Date limite de validation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_services",
                        to="members.member",
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worship_services",
                        to="events.event",
                        verbose_name="Événement associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Culte",
                "verbose_name_plural": "Cultes",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ServiceSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("order", models.PositiveIntegerField(verbose_name="Ordre")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("prelude", "Prélude"),
                            ("annonces", "Annonces"),
                            ("louange", "Louange"),
                            ("offrande", "Offrande"),
                            ("predication", "Prédication"),
                            ("communion", "Sainte Cène"),
                            ("priere", "Prière"),
                            ("benediction", "Bénédiction"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Type de section",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_sections",
                        to="members.department",
                        verbose_name="Département responsable",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="worship.worshipservice",
                        verbose_name="Culte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section de culte",
                "verbose_name_plural": "Sections de culte",
                "ordering": ["service", "order"],
                "unique_together": {("service", "order")},
            },
        ),
        migrations.CreateModel(
            name="ServiceAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigné"),
                            ("confirmed", "Confirmé"),
                            ("declined", "Non disponible"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Répondu le"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("reminder_5days_sent", models.BooleanField(default=False)),
                ("reminder_3days_sent", models.BooleanField(default=False)),
                ("reminder_1day_sent", models.BooleanField(default=False)),
                ("reminder_sameday_sent", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_assignments",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "task_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_assignments",
                        to="members.departmenttasktype",
                        verbose_name="Type de tâche",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="worship.servicesection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignation",
                "verbose_name_plural": "Assignations",
                "unique_together": {("section", "member")},
            },
        ),
    ]
