# Generated by Django 5.2.11 on 2026-02-14 05:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_eventtemplate_room_event_campus_event_is_hybrid_and_more"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
        ("worship", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SermonSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("start_date", models.DateField(verbose_name="Date de debut")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="worship/series/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serie de predications",
                "verbose_name_plural": "Series de predications",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                (
                    "artist",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Artiste"
                    ),
                ),
                (
                    "song_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C", "C"),
                            ("C#", "C#"),
                            ("D", "D"),
                            ("D#", "D#"),
                            ("E", "E"),
                            ("F", "F"),
                            ("F#", "F#"),
                            ("G", "G"),
                            ("G#", "G#"),
                            ("A", "A"),
                            ("A#", "A#"),
                            ("B", "B"),
                        ],
                        max_length=5,
                        verbose_name="Tonalite",
                    ),
                ),
                (
                    "bpm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="BPM"
                    ),
                ),
                ("lyrics", models.TextField(blank=True, verbose_name="Paroles")),
                (
                    "chord_chart",
                    models.TextField(blank=True, verbose_name="Grille d'accords"),
                ),
                (
                    "ccli_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numero CCLI"
                    ),
                ),
                (
                    "tags",
                    models.TextField(
                        blank=True,
                        help_text="Tags separes par des virgules",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "last_played",
                    models.DateField(
                        blank=True, null=True, verbose_name="Derniere utilisation"
                    ),
                ),
                (
                    "play_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de fois jouee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chant",
                "verbose_name_plural": "Chants",
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="eligiblememberlist",
            options={
                "verbose_name": "Liste d'eligibilite",
                "verbose_name_plural": "Listes d'eligibilite",
            },
        ),
        migrations.AlterField(
            model_name="eligiblememberlist",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eligible_lists",
                to="members.department",
                verbose_name="Departement",
            ),
        ),
        migrations.AlterField(
            model_name="eligiblememberlist",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="eligible_for_sections",
                to="members.member",
                verbose_name="Membres eligibles",
            ),
        ),
        migrations.AlterField(
            model_name="serviceassignment",
            name="responded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Repondu le"
            ),
        ),
        migrations.AlterField(
            model_name="serviceassignment",
            name="task_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_assignments",
                to="members.departmenttasktype",
                verbose_name="Type de tache",
            ),
        ),
        migrations.AlterField(
            model_name="servicesection",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_sections",
                to="members.department",
                verbose_name="Departement responsable",
            ),
        ),
        migrations.AlterField(
            model_name="servicesection",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=15, verbose_name="Duree (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="worshipservice",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_services",
                to="members.member",
                verbose_name="Cree par",
            ),
        ),
        migrations.AlterField(
            model_name="worshipservice",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=120, verbose_name="Duree (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="worshipservice",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worship_services",
                to="events.event",
                verbose_name="Evenement associe",
            ),
        ),
        migrations.AlterField(
            model_name="worshipservice",
            name="start_time",
            field=models.TimeField(verbose_name="Heure de debut"),
        ),
        migrations.AlterField(
            model_name="worshipservice",
            name="theme",
            field=models.CharField(blank=True, max_length=300, verbose_name="Theme"),
        ),
        migrations.AlterField(
            model_name="worshipservice",
            name="validation_deadline",
            field=models.DateField(
                blank=True,
                help_text="14 jours avant le culte par defaut",
                null=True,
                verbose_name="Date limite de validation",
            ),
        ),
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube Live"),
                            ("facebook", "Facebook Live"),
                            ("other", "Autre"),
                        ],
                        default="youtube",
                        max_length=20,
                        verbose_name="Plateforme",
                    ),
                ),
                ("stream_url", models.URLField(verbose_name="URL du flux")),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Debut du flux"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin du flux"
                    ),
                ),
                (
                    "viewer_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de spectateurs"
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(blank=True, verbose_name="URL de l'enregistrement"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livestreams",
                        to="worship.worshipservice",
                        verbose_name="Culte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diffusion en direct",
                "verbose_name_plural": "Diffusions en direct",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Rehearsal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de debut")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=300, verbose_name="Lieu"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rehearsals",
                        to="worship.worshipservice",
                        verbose_name="Culte associe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repetition",
                "verbose_name_plural": "Repetitions",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                (
                    "scripture_reference",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Reference biblique"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("audio_url", models.URLField(blank=True, verbose_name="URL audio")),
                ("video_url", models.URLField(blank=True, verbose_name="URL video")),
                ("notes", models.TextField(blank=True, verbose_name="Notes / Plan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duree (minutes)"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sermons",
                        to="worship.worshipservice",
                        verbose_name="Culte associe",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sermons",
                        to="members.member",
                        verbose_name="Predicateur",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sermons",
                        to="worship.sermonseries",
                        verbose_name="Serie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predication",
                "verbose_name_plural": "Predications",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Setlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setlist",
                        to="worship.worshipservice",
                        verbose_name="Culte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste de chants",
                "verbose_name_plural": "Listes de chants",
            },
        ),
        migrations.CreateModel(
            name="SongRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "song_title",
                    models.CharField(max_length=300, verbose_name="Titre du chant"),
                ),
                (
                    "artist",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Artiste"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("votes", models.PositiveIntegerField(default=0, verbose_name="Votes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("declined", "Refusée"),
                            ("scheduled", "Planifiée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date planifiee"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_requests",
                        to="members.member",
                        verbose_name="Demande par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de chant",
                "verbose_name_plural": "Demandes de chants",
                "ordering": ["-votes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "preferred_positions",
                    models.CharField(
                        blank=True,
                        help_text="Types de section separes par des virgules",
                        max_length=500,
                        verbose_name="Positions preferees",
                    ),
                ),
                (
                    "blackout_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de dates au format YYYY-MM-DD",
                        verbose_name="Dates indisponibles",
                    ),
                ),
                (
                    "max_services_per_month",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Maximum de cultes par mois"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worship_preference",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preference de volontaire",
                "verbose_name_plural": "Preferences de volontaires",
            },
        ),
        migrations.CreateModel(
            name="RehearsalAttendee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invité"),
                            ("confirmed", "Confirmé"),
                            ("declined", "Décliné"),
                        ],
                        default="invited",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rehearsal_attendances",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "rehearsal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="worship.rehearsal",
                        verbose_name="Repetition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant a la repetition",
                "verbose_name_plural": "Participants aux repetitions",
                "unique_together": {("rehearsal", "member")},
            },
        ),
        migrations.CreateModel(
            name="SetlistSong",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Ordre")),
                (
                    "key_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C", "C"),
                            ("C#", "C#"),
                            ("D", "D"),
                            ("D#", "D#"),
                            ("E", "E"),
                            ("F", "F"),
                            ("F#", "F#"),
                            ("G", "G"),
                            ("G#", "G#"),
                            ("A", "A"),
                            ("A#", "A#"),
                            ("B", "B"),
                        ],
                        max_length=5,
                        verbose_name="Tonalite (transposition)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "setlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="worship.setlist",
                        verbose_name="Liste de chants",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setlist_appearances",
                        to="worship.song",
                        verbose_name="Chant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chant dans la liste",
                "verbose_name_plural": "Chants dans la liste",
                "ordering": ["setlist", "order"],
                "unique_together": {("setlist", "order")},
            },
        ),
        migrations.CreateModel(
            name="SongRequestVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_request_votes",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "song_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records",
                        to="worship.songrequest",
                        verbose_name="Demande de chant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote de demande de chant",
                "verbose_name_plural": "Votes de demandes de chants",
                "unique_together": {("song_request", "member")},
            },
        ),
    ]
