# Generated by Django 5.2.11 on 2026-02-14 05:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchBranding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "church_name",
                    models.CharField(
                        help_text="Nom affiché dans l'en-tête et les documents",
                        max_length=200,
                        verbose_name="Nom de l'église",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de l'église (format recommandé: PNG, 200x200px)",
                        null=True,
                        upload_to="branding/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branding/favicons/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1a73e8",
                        help_text="Code hexadécimal (ex: #1a73e8)",
                        max_length=7,
                        verbose_name="Couleur primaire",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Code hexadécimal (ex: #6c757d)",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#28a745",
                        help_text="Code hexadécimal (ex: #28a745)",
                        max_length=7,
                        verbose_name="Couleur d'accent",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Courriel"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
            ],
            options={
                "verbose_name": "Image de marque",
                "verbose_name_plural": "Image de marque",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du campus"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "province",
                    models.CharField(blank=True, max_length=2, verbose_name="Province"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Courriel"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Campus principal"),
                ),
                (
                    "pastor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campus_pastor",
                        to="members.member",
                        verbose_name="Pasteur responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campus",
                "verbose_name_plural": "Campus",
                "ordering": ["-is_main", "name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom descriptif pour identifier ce webhook",
                        max_length=200,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["https", "http"]
                            )
                        ],
                        verbose_name="URL de destination",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Utilisée pour signer les requêtes (HMAC-SHA256)",
                        max_length=255,
                        verbose_name="Clé secrète",
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="Liste des événements déclencheurs",
                        verbose_name="Événements",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="En-têtes personnalisés"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Tentatives max"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point de terminaison webhook",
                "verbose_name_plural": "Points de terminaison webhook",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("restore", "Restauration"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("export", "Exportation"),
                            ("import", "Importation"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Nom du modèle affecté (ex: Member, Donation)",
                        max_length=100,
                        verbose_name="Modèle",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID de l'objet"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Représentation"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Détails des modifications (ancien/nouveau)",
                        verbose_name="Changements",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_auditl_user_id_969660_idx",
                    ),
                    models.Index(
                        fields=["model_name", "-created_at"],
                        name="core_auditl_model_n_a83f3d_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_auditl_action_d80c2d_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_auditl_created_1a76fa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("event", models.CharField(max_length=100, verbose_name="Événement")),
                ("payload", models.JSONField(default=dict, verbose_name="Contenu")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("success", "Succès"),
                            ("failed", "Échoué"),
                            ("retrying", "Nouvelle tentative"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Code de réponse"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="Corps de la réponse"),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Tentatives"),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière tentative"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.webhookendpoint",
                        verbose_name="Point de terminaison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison webhook",
                "verbose_name_plural": "Livraisons webhook",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "-created_at"],
                        name="core_webhoo_endpoin_a5c4ff_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_webhoo_status_538322_idx"
                    ),
                ],
            },
        ),
    ]
