# Generated by Django 5.0.6 on 2026-01-28 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('event_type', models.CharField(choices=[('worship', 'Culte'), ('group', 'Réunion de groupe'), ('meal', 'Repas communautaire'), ('special', 'Événement spécial'), ('meeting', 'Réunion'), ('training', 'Formation'), ('outreach', 'Évangélisation'), ('other', 'Autre')], default='worship', max_length=20, verbose_name='Type')),
                ('start_datetime', models.DateTimeField(verbose_name='Début')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='Toute la journée')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('location_address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_online', models.BooleanField(default=False, verbose_name='En ligne')),
                ('online_link', models.URLField(blank=True, verbose_name='Lien')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité max')),
                ('requires_rsvp', models.BooleanField(default=False, verbose_name='RSVP requis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', verbose_name='Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Annulé')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Récurrent')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='members.member', verbose_name='Organisateur')),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('declined', 'Refusé'), ('maybe', 'Peut-être')], default='pending', max_length=20, verbose_name='Statut')),
                ('guests', models.PositiveIntegerField(default=0, verbose_name='Invités')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event', verbose_name='Événement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'unique_together': {('event', 'member')},
            },
        ),
    ]
