# Generated by Django 5.2.11 on 2026-02-06 17:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/%Y/%m/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Image",
            ),
        ),
    ]
