# Generated by Django 5.2.11 on 2026-02-06 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "email_attempted",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email tenté"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("success", models.BooleanField(default=True, verbose_name="Réussi")),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Raison de l'échec"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("password", "Mot de passe"),
                            ("totp", "TOTP 2FA"),
                            ("social", "Compte social"),
                            ("code", "Code par email"),
                        ],
                        default="password",
                        max_length=30,
                        verbose_name="Méthode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit de connexion",
                "verbose_name_plural": "Audits de connexion",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_logina_user_id_1321e5_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_logina_created_c053a6_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="core_logina_ip_addr_7bd8e2_idx"
                    ),
                ],
            },
        ),
    ]
