# Generated by Django 5.2.11 on 2026-02-14 05:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GivingCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de la campagne"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Objectif",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant actuel",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "is_year_end",
                    models.BooleanField(
                        default=False, verbose_name="Campagne de fin d'année"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="giving_campaigns/%Y/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne de dons",
                "verbose_name_plural": "Campagnes de dons",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="KioskSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("session_date", models.DateField(verbose_name="Date de session")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "total_transactions",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de transactions"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "reconciled",
                    models.BooleanField(default=False, verbose_name="Réconcilié"),
                ),
                (
                    "reconciled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Réconcilié le"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Session kiosque",
                "verbose_name_plural": "Sessions kiosque",
                "ordering": ["-session_date"],
            },
        ),
        migrations.AddField(
            model_name="onlinepayment",
            name="payment_method_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="card, apple_pay, google_pay, ach_debit, etc.",
                max_length=30,
                verbose_name="Méthode de paiement",
            ),
        ),
        migrations.CreateModel(
            name="EmployerMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(max_length=200, verbose_name="Nom de l'employeur"),
                ),
                (
                    "match_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="ex: 1.00 = dollar pour dollar, 0.50 = 50 cents par dollar",
                        max_digits=5,
                        verbose_name="Ratio de jumelage",
                    ),
                ),
                (
                    "annual_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="0 = pas de plafond",
                        max_digits=12,
                        verbose_name="Plafond annuel",
                    ),
                ),
                (
                    "match_amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant de jumelage reçu",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_matches",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jumelage employeur",
                "verbose_name_plural": "Jumelages employeur",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant total"
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant par versement",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Hebdomadaire"),
                            ("biweekly", "Aux deux semaines"),
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("annually", "Annuel"),
                            ("one_time", "Unique"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant restant"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("completed", "Complété"),
                            ("defaulted", "En défaut"),
                            ("cancelled", "Annulé"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Complété le"
                    ),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("tithe", "Dîme"),
                            ("offering", "Offrande générale"),
                            ("special", "Offrande spéciale"),
                            ("campaign", "Campagne"),
                            ("building", "Bâtiment"),
                            ("missions", "Missions"),
                            ("other", "Autre"),
                        ],
                        default="offering",
                        max_length=20,
                        verbose_name="Type de don",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de paiement",
                "verbose_name_plural": "Plans de paiement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Numéro de téléphone"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Stripe Charge ID",
                    ),
                ),
                (
                    "command_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Texte original du SMS reçu",
                        max_length=200,
                        verbose_name="Commande SMS",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Récurrent"),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[("weekly", "Hebdomadaire"), ("monthly", "Mensuel")],
                        default="",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_donations",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Don par SMS",
                "verbose_name_plural": "Dons par SMS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GivingGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Année")),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant cible"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giving_goals",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif de don",
                "verbose_name_plural": "Objectifs de don",
                "ordering": ["-year"],
                "unique_together": {("member", "year")},
            },
        ),
        migrations.CreateModel(
            name="GivingStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de la période")),
                ("period_end", models.DateField(verbose_name="Fin de la période")),
                (
                    "statement_type",
                    models.CharField(
                        choices=[("quarterly", "Trimestriel"), ("annual", "Annuel")],
                        default="annual",
                        max_length=20,
                        verbose_name="Type de relevé",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Généré le"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="statements/%Y/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Envoyé le"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giving_statements",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relevé de dons",
                "verbose_name_plural": "Relevés de dons",
                "ordering": ["-period_end", "-generated_at"],
                "unique_together": {
                    ("member", "period_start", "period_end", "statement_type")
                },
            },
        ),
    ]
