# Generated by Django 5.2.11 on 2026-02-06 17:59

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_member_admin_reviewed_at_member_admin_reviewed_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Numéro de la leçon dans le parcours",
                        verbose_name="Ordre",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "materials_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lessons/pdf/%Y/",
                        validators=[apps.core.validators.validate_pdf_file],
                        verbose_name="Document PDF",
                    ),
                ),
                (
                    "materials_notes",
                    models.TextField(blank=True, verbose_name="Notes de cours"),
                ),
            ],
            options={
                "verbose_name": "Leçon",
                "verbose_name_plural": "Leçons",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="MemberTraining",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigné le"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Complété le"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Complété"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_trainings",
                        to="members.member",
                        verbose_name="Assigné par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation membre",
                "verbose_name_plural": "Formations membres",
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Date proposée"),
                            ("accepted", "Acceptée"),
                            ("counter", "Contre-proposition"),
                            ("confirmed", "Confirmée"),
                            ("passed", "Réussie"),
                            ("failed", "Échouée"),
                            ("no_show", "Absent"),
                            ("cancelled", "Annulée"),
                        ],
                        default="proposed",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("proposed_date", models.DateTimeField(verbose_name="Date proposée")),
                (
                    "counter_proposed_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Contre-proposition du membre",
                    ),
                ),
                (
                    "confirmed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date confirmée"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Complété le"
                    ),
                ),
                (
                    "result_notes",
                    models.TextField(blank=True, verbose_name="Notes de résultat"),
                ),
                ("reminder_3days_sent", models.BooleanField(default=False)),
                ("reminder_1day_sent", models.BooleanField(default=False)),
                ("reminder_sameday_sent", models.BooleanField(default=False)),
                (
                    "interviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_interviews",
                        to="members.member",
                        verbose_name="Intervieweur",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="onboarding.membertraining",
                        verbose_name="Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview",
                "verbose_name_plural": "Interviews",
                "ordering": ["-proposed_date"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Date et heure prévue"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "À venir"),
                            ("completed", "Complétée"),
                            ("absent", "Absent"),
                            ("makeup", "Rattrapage"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "attended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Présent à"
                    ),
                ),
                (
                    "is_makeup",
                    models.BooleanField(
                        default=False, verbose_name="Session de rattrapage"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("reminder_3days_sent", models.BooleanField(default=False)),
                ("reminder_1day_sent", models.BooleanField(default=False)),
                ("reminder_sameday_sent", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_instances",
                        to="onboarding.lesson",
                        verbose_name="Leçon",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_lessons",
                        to="members.member",
                        verbose_name="Marqué par",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_lessons",
                        to="onboarding.membertraining",
                        verbose_name="Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leçon planifiée",
                "verbose_name_plural": "Leçons planifiées",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Parcours Découverte 2025",
                        max_length=200,
                        verbose_name="Nom du parcours",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "total_lessons",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Nombre de leçons"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Utilisé automatiquement pour les nouveaux membres",
                        verbose_name="Parcours par défaut",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_courses",
                        to="members.member",
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcours de formation",
                "verbose_name_plural": "Parcours de formation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="membertraining",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="onboarding.trainingcourse",
                verbose_name="Parcours",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="onboarding.trainingcourse",
                verbose_name="Parcours",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membertraining",
            unique_together={("member", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("course", "order")},
        ),
    ]
