# Generated by Django 5.2.11 on 2026-02-07 14:25

import apps.onboarding.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_member_membership_status_alter_member_role_and_more"),
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.onboarding.models._generate_invitation_code,
                        max_length=32,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Membre"),
                            ("volunteer", "Volontaire"),
                            ("group_leader", "Leader de groupe"),
                            ("deacon", "Diacre"),
                            ("pastor", "Pasteur"),
                            ("treasurer", "Trésorier"),
                            ("admin", "Administrateur"),
                        ],
                        default="member",
                        help_text="Rôle attribué au membre lors de l'utilisation",
                        max_length=20,
                        verbose_name="Rôle assigné",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Utilisé le"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Utilisations max"
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'utilisations"
                    ),
                ),
                (
                    "skip_onboarding",
                    models.BooleanField(
                        default=False,
                        help_text="Si coché, le membre devient actif immédiatement (membres pré-existants)",
                        verbose_name="Passer le parcours",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invitations",
                        to="members.member",
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_invitations",
                        to="members.member",
                        verbose_name="Utilisé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code d'invitation",
                "verbose_name_plural": "Codes d'invitation",
                "ordering": ["-created_at"],
            },
        ),
    ]
