# Generated by Django 5.2.11 on 2026-02-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerschedule",
            name="reminder_1day_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteerschedule",
            name="reminder_3days_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteerschedule",
            name="reminder_5days_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteerschedule",
            name="reminder_sameday_sent",
            field=models.BooleanField(default=False),
        ),
    ]
