# Generated by Django 5.2.11 on 2026-02-14 05:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
        ("volunteers", "0003_planned_absence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Categorie"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Competence",
                "verbose_name_plural": "Competences",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="plannedabsence",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Absence prevue",
                "verbose_name_plural": "Absences prevues",
            },
        ),
        migrations.AlterModelOptions(
            name="swaprequest",
            options={
                "verbose_name": "Demande d'echange",
                "verbose_name_plural": "Demandes d'echange",
            },
        ),
        migrations.AlterModelOptions(
            name="volunteeravailability",
            options={
                "verbose_name": "Disponibilite",
                "verbose_name_plural": "Disponibilites",
            },
        ),
        migrations.AlterModelOptions(
            name="volunteerposition",
            options={
                "ordering": ["name"],
                "verbose_name": "Poste de benevolat",
                "verbose_name_plural": "Postes de benevolat",
            },
        ),
        migrations.AlterField(
            model_name="plannedabsence",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_absences",
                to="members.member",
                verbose_name="Approuve par",
            ),
        ),
        migrations.AlterField(
            model_name="plannedabsence",
            name="start_date",
            field=models.DateField(verbose_name="Date de debut"),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuve"),
                    ("declined", "Refuse"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="volunteeravailability",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Chaque semaine"),
                    ("biweekly", "Aux deux semaines"),
                    ("monthly", "Une fois par mois"),
                    ("occasional", "Occasionnellement"),
                ],
                default="monthly",
                max_length=20,
                verbose_name="Frequence",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerposition",
            name="skills_required",
            field=models.TextField(blank=True, verbose_name="Competences requises"),
        ),
        migrations.AlterField(
            model_name="volunteerschedule",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Rappel envoye"),
        ),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="Jour",
                    ),
                ),
                ("time_start", models.TimeField(verbose_name="Heure de debut")),
                ("time_end", models.TimeField(verbose_name="Heure de fin")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plage de disponibilite",
                "verbose_name_plural": "Plages de disponibilite",
                "ordering": ["day_of_week", "time_start"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("hours", "Heures de service"),
                            ("years", "Années de service"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        help_text="Nombre d'heures ou d'annees", verbose_name="Seuil"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "badge_icon",
                    models.CharField(
                        blank=True,
                        help_text="Classe CSS FontAwesome",
                        max_length=100,
                        verbose_name="Icone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jalon",
                "verbose_name_plural": "Jalons",
                "ordering": ["milestone_type", "threshold"],
                "unique_together": {("milestone_type", "threshold")},
            },
        ),
        migrations.CreateModel(
            name="PositionChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Requis"),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="volunteers.volunteerposition",
                        verbose_name="Poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element de checklist",
                "verbose_name_plural": "Elements de checklist",
                "ordering": ["position", "order"],
            },
        ),
        migrations.CreateModel(
            name="TeamAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("body", models.TextField(verbose_name="Message")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_announcements",
                        to="members.member",
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="volunteers.volunteerposition",
                        verbose_name="Poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce d'equipe",
                "verbose_name_plural": "Annonces d'equipe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerBackgroundCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_required", "Non requis"),
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("expired", "Expiré"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "check_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de verification"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_background_checks",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_checks",
                        to="volunteers.volunteerposition",
                        verbose_name="Poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification des antecedents",
                "verbose_name_plural": "Verifications des antecedents",
                "ordering": ["-check_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Heures travaillees",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'approbation"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_hours",
                        to="members.member",
                        verbose_name="Approuve par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_hours",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logged_hours",
                        to="volunteers.volunteerposition",
                        verbose_name="Poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Heures de benevolat",
                "verbose_name_plural": "Heures de benevolat",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CrossTraining",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "certified_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de certification"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_trainings",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "original_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_training_from",
                        to="volunteers.volunteerposition",
                        verbose_name="Poste original",
                    ),
                ),
                (
                    "trained_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_training_to",
                        to="volunteers.volunteerposition",
                        verbose_name="Poste forme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation croisee",
                "verbose_name_plural": "Formations croisees",
                "unique_together": {
                    ("member", "original_position", "trained_position")
                },
            },
        ),
        migrations.CreateModel(
            name="MilestoneAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("achieved_at", models.DateTimeField(verbose_name="Atteint le")),
                (
                    "notified",
                    models.BooleanField(default=False, verbose_name="Notifie"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_achievements",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="volunteers.milestone",
                        verbose_name="Jalon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jalon atteint",
                "verbose_name_plural": "Jalons atteints",
                "ordering": ["-achieved_at"],
                "unique_together": {("member", "milestone")},
            },
        ),
        migrations.CreateModel(
            name="ChecklistProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Complete le"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_progress",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_checklist_items",
                        to="members.member",
                        verbose_name="Verifie par",
                    ),
                ),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="volunteers.positionchecklist",
                        verbose_name="Element",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progres de checklist",
                "verbose_name_plural": "Progres de checklist",
                "unique_together": {("member", "checklist_item")},
            },
        ),
        migrations.CreateModel(
            name="VolunteerSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Débutant"),
                            ("intermediate", "Intermédiaire"),
                            ("advanced", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "certified_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de certification"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_skills",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_skills",
                        to="volunteers.skill",
                        verbose_name="Competence",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_skills",
                        to="members.member",
                        verbose_name="Verifie par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competence de benevole",
                "verbose_name_plural": "Competences de benevoles",
                "unique_together": {("member", "skill")},
            },
        ),
    ]
