# Generated by Django 5.0.6 on 2026-01-28 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('name', models.CharField(help_text='Ex: Famille Dupont', max_length=200, verbose_name='Nom de famille')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'Colombie-Britannique'), ('MB', 'Manitoba'), ('NB', 'Nouveau-Brunswick'), ('NL', 'Terre-Neuve-et-Labrador'), ('NS', 'Nouvelle-Écosse'), ('NT', 'Territoires du Nord-Ouest'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Île-du-Prince-Édouard'), ('QC', 'Québec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='QC', max_length=2, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du groupe')),
                ('group_type', models.CharField(choices=[('cell', 'Cellule'), ('ministry', 'Ministère'), ('committee', 'Comité'), ('class', 'Classe'), ('choir', 'Chorale'), ('other', 'Autre')], default='cell', max_length=20, verbose_name='Type de groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('meeting_day', models.CharField(blank=True, max_length=20, verbose_name='Jour de réunion')),
                ('meeting_time', models.TimeField(blank=True, null=True, verbose_name='Heure de réunion')),
                ('meeting_location', models.CharField(blank=True, max_length=200, verbose_name='Lieu de réunion')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel du groupe')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date à laquelle cet enregistrement a été supprimé', null=True, verbose_name='Date de suppression')),
                ('member_number', models.CharField(editable=False, help_text='Généré automatiquement', max_length=20, unique=True, verbose_name='Numéro de membre')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'Colombie-Britannique'), ('MB', 'Manitoba'), ('NB', 'Nouveau-Brunswick'), ('NL', 'Terre-Neuve-et-Labrador'), ('NS', 'Nouvelle-Écosse'), ('NT', 'Territoires du Nord-Ouest'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Île-du-Prince-Édouard'), ('QC', 'Québec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='QC', max_length=2, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/%Y/%m/', verbose_name='Photo')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('volunteer', 'Volontaire'), ('group_leader', 'Leader de groupe'), ('pastor', 'Pasteur'), ('treasurer', 'Trésorier'), ('admin', 'Administrateur')], default='member', max_length=20, verbose_name='Rôle')),
                ('family_status', models.CharField(choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('widowed', 'Veuf/Veuve'), ('divorced', 'Divorcé(e)')], default='single', max_length=20, verbose_name='État civil')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name="Date d'adhésion")),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Date de baptême')),
                ('notes', models.TextField(blank=True, help_text="Visible uniquement par l'équipe pastorale", verbose_name='Notes pastorales')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.family', verbose_name='Famille')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('leader', 'Leader'), ('assistant', 'Assistant')], default='member', max_length=20, verbose_name='Rôle dans le groupe')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.group', verbose_name='Groupe')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Adhésion au groupe',
                'verbose_name_plural': 'Adhésions aux groupes',
                'ordering': ['group__name', 'member__last_name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='members.member', verbose_name='Leader'),
        ),
        migrations.CreateModel(
            name='DirectoryPrivacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('visibility', models.CharField(choices=[('public', 'Public (tous les membres)'), ('group', 'Groupe (mes groupes seulement)'), ('private', 'Privé (équipe pastorale seulement)')], default='public', max_length=20, verbose_name='Visibilité du profil')),
                ('show_email', models.BooleanField(default=True, verbose_name='Afficher le courriel')),
                ('show_phone', models.BooleanField(default=True, verbose_name='Afficher le téléphone')),
                ('show_address', models.BooleanField(default=False, verbose_name="Afficher l'adresse")),
                ('show_birth_date', models.BooleanField(default=True, verbose_name='Afficher la date de naissance')),
                ('show_photo', models.BooleanField(default=True, verbose_name='Afficher la photo')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Paramètres de confidentialité',
                'verbose_name_plural': 'Paramètres de confidentialité',
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_number'], name='members_mem_member__425bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='members_mem_email_afed21_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_92a910_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['birth_date'], name='members_mem_birth_d_9747cd_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['role'], name='members_mem_role_241778_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('member', 'group')},
        ),
    ]
