# Generated by Django 5.2.11 on 2026-02-06 17:59

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="admin_reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Révisé par admin le"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="admin_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_members",
                to="members.member",
                verbose_name="Révisé par",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="became_active_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Devenu membre actif le"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="form_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date limite formulaire"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="form_submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Formulaire soumis le"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("registered", "Inscrit"),
                    ("form_pending", "Formulaire en attente"),
                    ("form_submitted", "Formulaire soumis"),
                    ("in_review", "En cours de révision"),
                    ("approved", "Approuvé"),
                    ("in_training", "En formation"),
                    ("interview_scheduled", "Interview planifiée"),
                    ("active", "Membre actif"),
                    ("suspended", "Suspendu"),
                    ("rejected", "Refusé"),
                    ("expired", "Expiré"),
                ],
                db_index=True,
                default="registered",
                max_length=30,
                verbose_name="Statut d'adhésion",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="registration_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'inscription"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Raison du refus"),
        ),
        migrations.AlterField(
            model_name="member",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="members/photos/%Y/%m/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Photo",
            ),
        ),
    ]
