# Generated by Django 5.2.11 on 2026-02-07 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_two_factor_deadline_member_two_factor_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("registered", "Inscrit"),
                    ("form_pending", "Formulaire en attente"),
                    ("form_submitted", "Formulaire soumis"),
                    ("in_review", "En cours de révision"),
                    ("approved", "Approuvé"),
                    ("in_training", "En formation"),
                    ("interview_scheduled", "Interview planifiée"),
                    ("active", "Membre actif"),
                    ("inactive", "Inactif"),
                    ("suspended", "Suspendu"),
                    ("rejected", "Refusé"),
                    ("expired", "Expiré"),
                ],
                db_index=True,
                default="registered",
                max_length=30,
                verbose_name="Statut d'adhésion",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Membre"),
                    ("volunteer", "Volontaire"),
                    ("group_leader", "Leader de groupe"),
                    ("deacon", "Diacre"),
                    ("pastor", "Pasteur"),
                    ("treasurer", "Trésorier"),
                    ("admin", "Administrateur"),
                ],
                default="member",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "meeting_day",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Jour de réunion"
                    ),
                ),
                (
                    "meeting_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de réunion"
                    ),
                ),
                (
                    "meeting_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Lieu de réunion"
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_departments",
                        to="members.member",
                        verbose_name="Leader",
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_departments",
                        to="members.department",
                        verbose_name="Département parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DisciplinaryAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("punishment", "Punition"),
                            ("exemption", "Exemption"),
                            ("suspension", "Suspension"),
                        ],
                        max_length=20,
                        verbose_name="Type d'action",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif")),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut d'approbation",
                    ),
                ),
                (
                    "auto_suspend_membership",
                    models.BooleanField(
                        default=True, verbose_name="Suspendre automatiquement le compte"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_disciplinary_actions",
                        to="members.member",
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_disciplinary_actions",
                        to="members.member",
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_actions",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action disciplinaire",
                "verbose_name_plural": "Actions disciplinaires",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Membre"),
                            ("leader", "Leader"),
                            ("assistant", "Assistant"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "joined_date",
                    models.DateField(auto_now_add=True, verbose_name="Date d'adhésion"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="members.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_memberships",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adhésion au département",
                "verbose_name_plural": "Adhésions aux départements",
                "ordering": ["department__name"],
                "unique_together": {("member", "department")},
            },
        ),
        migrations.CreateModel(
            name="DepartmentTaskType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la tâche"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "max_assignees",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre max d'assignés"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_types",
                        to="members.department",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de tâche",
                "verbose_name_plural": "Types de tâches",
                "ordering": ["department", "name"],
                "unique_together": {("department", "name")},
            },
        ),
        migrations.CreateModel(
            name="MemberRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Membre"),
                            ("volunteer", "Volontaire"),
                            ("group_leader", "Leader de groupe"),
                            ("deacon", "Diacre"),
                            ("pastor", "Pasteur"),
                            ("treasurer", "Trésorier"),
                            ("admin", "Administrateur"),
                        ],
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_roles",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle supplémentaire",
                "verbose_name_plural": "Rôles supplémentaires",
                "unique_together": {("member", "role")},
            },
        ),
    ]
