# Generated by Django 5.2.11 on 2026-02-07 14:32

from django.db import migrations


DEFAULT_DEPARTMENTS = [
    ('Administration', 'Gestion administrative de l\'église'),
    ('Maintenance', 'Entretien des bâtiments et équipements'),
    ('Marketing', 'Communication externe et promotion'),
    ('Multimédia', 'Production audiovisuelle, streaming, réseaux sociaux'),
    ('Accueil', 'Accueil des visiteurs et nouveaux membres'),
    ('Louange', 'Direction de la louange et adoration'),
    ('Intercession', 'Prière et intercession'),
    ('Enfants', 'Ministère des enfants et école du dimanche'),
    ('Jeunesse', 'Ministère des jeunes et adolescents'),
    ('Cuisine', 'Préparation des repas et réceptions'),
    ('Décoration', 'Décoration de la salle et événements'),
    ('Transport', 'Transport des membres et logistique'),
    ('Sécurité', 'Sécurité et protocole'),
    ('Protocole', 'Organisation des cérémonies et protocole'),
    ('Chorale', 'Chorale et chants spéciaux'),
    ('Orchestre', 'Musiciens et instrumentistes'),
    ('Son/Technique', 'Sonorisation et équipement technique'),
    ('Diaconie', 'Service social et aide aux démunis'),
    ('Évangélisation', 'Mission et évangélisation'),
    ('Formation', 'Formation des membres et discipleship'),
    ('Communication', 'Communication interne, bulletins, annonces'),
    ('Finances', 'Gestion financière et comptabilité'),
    ('Conseil pastoral', 'Conseil et accompagnement pastoral'),
    ('Nettoyage', 'Nettoyage et hygiène des locaux'),
    ('Logistique', 'Organisation matérielle et logistique des événements'),
]


def create_departments(apps, schema_editor):
    Department = apps.get_model('members', 'Department')
    for name, description in DEFAULT_DEPARTMENTS:
        Department.objects.get_or_create(
            name=name,
            defaults={'description': description},
        )


def remove_departments(apps, schema_editor):
    Department = apps.get_model('members', 'Department')
    Department.objects.filter(
        name__in=[name for name, _ in DEFAULT_DEPARTMENTS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_member_membership_status_alter_member_role_and_more"),
    ]

    operations = [
        migrations.RunPython(create_departments, remove_departments),
    ]
