# Generated by Django 5.2.11 on 2026-02-07 22:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_default_departments"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileModificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Décrivez les modifications demandées",
                        verbose_name="Message",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Complété"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Complété le"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_modification_requests",
                        to="members.member",
                        verbose_name="Demandé par",
                    ),
                ),
                (
                    "target_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification_requests",
                        to="members.member",
                        verbose_name="Membre cible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de modification de profil",
                "verbose_name_plural": "Demandes de modification de profil",
                "ordering": ["-created_at"],
            },
        ),
    ]
