# Generated by Django 5.2.11 on 2026-02-14 05:03

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_profilemodificationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom du champ")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texte court"),
                            ("textarea", "Texte long"),
                            ("number", "Nombre"),
                            ("date", "Date"),
                            ("dropdown", "Liste déroulante"),
                            ("checkbox", "Case à cocher"),
                            ("file", "Fichier"),
                        ],
                        max_length=20,
                        verbose_name="Type de champ",
                    ),
                ),
                (
                    "options_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Options pour liste déroulante (format JSON)",
                        verbose_name="Options",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Obligatoire"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ personnalisé",
                "verbose_name_plural": "Champs personnalisés",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="lifecycle_stage",
            field=models.CharField(
                choices=[
                    ("launching", "En lancement"),
                    ("active", "Actif"),
                    ("multiplying", "En multiplication"),
                    ("closed", "Fermé"),
                ],
                default="active",
                max_length=20,
                verbose_name="Étape du cycle de vie",
            ),
        ),
        migrations.CreateModel(
            name="BackgroundCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_required", "Non requis"),
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("expired", "Expiré"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "check_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de vérification"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Fournisseur"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de référence"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_checks",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vérification des antécédents",
                "verbose_name_plural": "Vérifications des antécédents",
                "ordering": ["-check_date"],
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Liste des allergies connues",
                        verbose_name="Allergies",
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Conditions médicales, médicaments, etc.",
                        verbose_name="Notes médicales",
                    ),
                ),
                (
                    "authorized_pickups",
                    models.TextField(
                        blank=True,
                        help_text="Personnes autorisées à récupérer l'enfant",
                        verbose_name="Personnes autorisées",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/children/%Y/%m/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="Photo",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="members.family",
                        verbose_name="Famille",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enfant",
                "verbose_name_plural": "Enfants",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ImportHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Fichier")),
                (
                    "total_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de lignes"
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="Réussis"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="Erreurs"),
                ),
                (
                    "errors_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Détails des erreurs"
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_operations",
                        to="members.member",
                        verbose_name="Importé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'importation",
                "verbose_name_plural": "Historiques d'importation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberEngagementScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "attendance_score",
                    models.FloatField(default=0, verbose_name="Score de présence"),
                ),
                (
                    "giving_score",
                    models.FloatField(default=0, verbose_name="Score de dons"),
                ),
                (
                    "volunteering_score",
                    models.FloatField(default=0, verbose_name="Score de bénévolat"),
                ),
                (
                    "group_score",
                    models.FloatField(default=0, verbose_name="Score de groupe"),
                ),
                (
                    "total_score",
                    models.FloatField(default=0, verbose_name="Score total"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Calculé le"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_score",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score d'engagement",
                "verbose_name_plural": "Scores d'engagement",
                "ordering": ["-total_score"],
            },
        ),
        migrations.CreateModel(
            name="MemberMergeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "merged_member_data",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot des données avant fusion",
                        verbose_name="Données du membre fusionné",
                    ),
                ),
                (
                    "merged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_merges",
                        to="members.member",
                        verbose_name="Fusionné par",
                    ),
                ),
                (
                    "primary_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_primary_logs",
                        to="members.member",
                        verbose_name="Membre principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de fusion",
                "verbose_name_plural": "Journaux de fusion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PastoralCare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "care_type",
                    models.CharField(
                        choices=[
                            ("hospital_visit", "Visite à l'hôpital"),
                            ("home_visit", "Visite à domicile"),
                            ("phone_call", "Appel téléphonique"),
                            ("counseling", "Counseling"),
                            ("prayer_meeting", "Rencontre de prière"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Type de soin",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de suivi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("follow_up", "Suivi"),
                            ("closed", "Fermé"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_care_records",
                        to="members.member",
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastoral_care_records",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soin pastoral",
                "verbose_name_plural": "Soins pastoraux",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Valeur")),
                (
                    "custom_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="members.customfield",
                        verbose_name="Champ personnalisé",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur de champ personnalisé",
                "verbose_name_plural": "Valeurs de champs personnalisés",
                "unique_together": {("member", "custom_field")},
            },
        ),
    ]
