# Generated by Django 5.2.11 on 2026-02-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_invitation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="reminder_5days_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheduledlesson",
            name="reminder_5days_sent",
            field=models.BooleanField(default=False),
        ),
    ]
