# Generated by Django 5.2.11 on 2026-02-14 05:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
        ("onboarding", "0003_interview_reminder_5days_sent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Classe CSS de l'icone (ex: fas fa-star)",
                        max_length=50,
                        verbose_name="Icone",
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/badges/",
                        verbose_name="Image du badge",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=10, verbose_name="Points"),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("form_submitted", "Formulaire soumis"),
                            ("training_started", "Formation commencée"),
                            ("lesson_completed", "Leçon complétée"),
                            ("training_completed", "Formation complétée"),
                            ("interview_passed", "Interview réussie"),
                            ("became_active", "Devenu membre actif"),
                            ("first_attendance", "Première présence"),
                            ("mentor_assigned", "Mentor assigné"),
                            ("document_signed", "Document signé"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=30,
                        verbose_name="Type de declencheur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accomplissement",
                "verbose_name_plural": "Accomplissements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "requires_signature",
                    models.BooleanField(default=True, verbose_name="Signature requise"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("covenant", "Alliance"),
                            ("policy", "Politique"),
                            ("consent", "Consentement"),
                            ("waiver", "Décharge"),
                            ("other", "Autre"),
                        ],
                        default="covenant",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document d'integration",
                "verbose_name_plural": "Documents d'integration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WelcomeSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de la sequence"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Sequence de bienvenue",
                "verbose_name_plural": "Sequences de bienvenue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["course", "order"],
                "verbose_name": "Lecon",
                "verbose_name_plural": "Lecons",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduledlesson",
            options={
                "ordering": ["scheduled_date"],
                "verbose_name": "Lecon planifiee",
                "verbose_name_plural": "Lecons planifiees",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Lien YouTube ou Vimeo pour la video de la lecon",
                verbose_name="URL de la video",
            ),
        ),
        migrations.AddField(
            model_name="scheduledlesson",
            name="video_completed",
            field=models.BooleanField(default=False, verbose_name="Video vue"),
        ),
        migrations.AddField(
            model_name="scheduledlesson",
            name="video_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Video vue le"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Complete le"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="confirmed_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date confirmee"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="proposed_date",
            field=models.DateTimeField(verbose_name="Date proposee"),
        ),
        migrations.AlterField(
            model_name="interview",
            name="result_notes",
            field=models.TextField(blank=True, verbose_name="Notes de resultat"),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_invitations",
                to="members.member",
                verbose_name="Cree par",
            ),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Membre"),
                    ("volunteer", "Volontaire"),
                    ("group_leader", "Leader de groupe"),
                    ("deacon", "Diacre"),
                    ("pastor", "Pasteur"),
                    ("treasurer", "Trésorier"),
                    ("admin", "Administrateur"),
                ],
                default="member",
                help_text="Role attribue au membre lors de l'utilisation",
                max_length=20,
                verbose_name="Role assigne",
            ),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="skip_onboarding",
            field=models.BooleanField(
                default=False,
                help_text="Si coche, le membre devient actif immediatement (membres pre-existants)",
                verbose_name="Passer le parcours",
            ),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="used_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Utilise le"
            ),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_invitations",
                to="members.member",
                verbose_name="Utilise par",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=90, verbose_name="Duree (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Numero de la lecon dans le parcours", verbose_name="Ordre"
            ),
        ),
        migrations.AlterField(
            model_name="membertraining",
            name="assigned_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Assigne le"),
        ),
        migrations.AlterField(
            model_name="membertraining",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_trainings",
                to="members.member",
                verbose_name="Assigne par",
            ),
        ),
        migrations.AlterField(
            model_name="membertraining",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Complete le"
            ),
        ),
        migrations.AlterField(
            model_name="membertraining",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Complete"),
        ),
        migrations.AlterField(
            model_name="scheduledlesson",
            name="attended_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Present a"),
        ),
        migrations.AlterField(
            model_name="scheduledlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_instances",
                to="onboarding.lesson",
                verbose_name="Lecon",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledlesson",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_lessons",
                to="members.member",
                verbose_name="Marque par",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledlesson",
            name="scheduled_date",
            field=models.DateTimeField(verbose_name="Date et heure prevue"),
        ),
        migrations.AlterField(
            model_name="trainingcourse",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_courses",
                to="members.member",
                verbose_name="Cree par",
            ),
        ),
        migrations.AlterField(
            model_name="trainingcourse",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Utilise automatiquement pour les nouveaux membres",
                verbose_name="Parcours par defaut",
            ),
        ),
        migrations.AlterField(
            model_name="trainingcourse",
            name="name",
            field=models.CharField(
                help_text="Ex: Parcours Decouverte 2025",
                max_length=200,
                verbose_name="Nom du parcours",
            ),
        ),
        migrations.AlterField(
            model_name="trainingcourse",
            name="total_lessons",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Nombre de lecons"
            ),
        ),
        migrations.CreateModel(
            name="MentorAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date de debut"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("completed", "Complété"),
                            ("cancelled", "Annulé"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "check_in_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de suivis"
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_assignments_as_mentor",
                        to="members.member",
                        verbose_name="Mentor",
                    ),
                ),
                (
                    "new_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_assignments_as_mentee",
                        to="members.member",
                        verbose_name="Nouveau membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignation de mentor",
                "verbose_name_plural": "Assignations de mentor",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="onboarding.mentorassignment",
                        verbose_name="Assignation",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_checkins",
                        to="members.member",
                        verbose_name="Note par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi mentor",
                "verbose_name_plural": "Suivis mentor",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingFormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Libelle")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texte court"),
                            ("textarea", "Texte long"),
                            ("number", "Nombre"),
                            ("date", "Date"),
                            ("dropdown", "Liste déroulante"),
                            ("checkbox", "Case à cocher"),
                            ("file", "Fichier"),
                        ],
                        max_length=20,
                        verbose_name="Type de champ",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Obligatoire"),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de choix pour les listes deroulantes (JSON array)",
                        verbose_name="Options",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "conditional_value",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Valeur conditionnelle"
                    ),
                ),
                (
                    "conditional_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ce champ ne s'affiche que si le champ conditionnel a la valeur specifiee",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_fields",
                        to="onboarding.onboardingformfield",
                        verbose_name="Champ conditionnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ de formulaire",
                "verbose_name_plural": "Champs de formulaire",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingTrackModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du parcours"),
                ),
                (
                    "track_type",
                    models.CharField(
                        choices=[
                            ("new_believer", "Nouveau croyant"),
                            ("transfer", "Transfert d'église"),
                            ("youth", "Jeunesse"),
                            ("family", "Famille"),
                            ("default", "Standard"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="Type de parcours",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tracks",
                        to="onboarding.trainingcourse",
                        verbose_name="Formations associees",
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tracks",
                        to="onboarding.onboardingdocument",
                        verbose_name="Documents associes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcours multi-piste",
                "verbose_name_plural": "Parcours multi-pistes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="membertraining",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_enrollments",
                to="onboarding.onboardingtrackmodel",
                verbose_name="Parcours multi-piste",
            ),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70, verbose_name="Score de reussite (%)"
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="onboarding.lesson",
                        verbose_name="Lecon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=0, verbose_name="Score (%)"),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="Reussi")),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="Mapping question_id -> answer_id",
                        verbose_name="Reponses",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Termine le"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="onboarding.quiz",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative de quiz",
                "verbose_name_plural": "Tentatives de quiz",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("text", models.TextField(verbose_name="Question")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="onboarding.quiz",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question de quiz",
                "verbose_name_plural": "Questions de quiz",
                "ordering": ["quiz", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Reponse")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Correcte"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="onboarding.quizquestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reponse de quiz",
                "verbose_name_plural": "Reponses de quiz",
            },
        ),
        migrations.CreateModel(
            name="VisitorFollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(max_length=200, verbose_name="Nom du visiteur"),
                ),
                (
                    "visitor_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Courriel du visiteur"
                    ),
                ),
                (
                    "visitor_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telephone du visiteur"
                    ),
                ),
                (
                    "first_visit_date",
                    models.DateField(verbose_name="Date de la premiere visite"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours"),
                            ("completed", "Complété"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Converti le"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_followups",
                        to="members.member",
                        verbose_name="Assigne a",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si le visiteur a cree un profil membre",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_profile",
                        to="members.member",
                        verbose_name="Profil membre cree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de visiteur",
                "verbose_name_plural": "Suivis de visiteurs",
                "ordering": ["-first_visit_date"],
            },
        ),
        migrations.CreateModel(
            name="WelcomeStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "day_offset",
                    models.PositiveIntegerField(
                        help_text="Nombre de jours apres l'inscription pour envoyer ce message",
                        verbose_name="Jour (apres inscription)",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Courriel"),
                            ("sms", "SMS"),
                            ("both", "Courriel et SMS"),
                        ],
                        default="email",
                        max_length=10,
                        verbose_name="Canal",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                (
                    "body",
                    models.TextField(
                        help_text="Utilisez {{ member_name }} pour le nom du membre",
                        verbose_name="Corps du message",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="onboarding.welcomesequence",
                        verbose_name="Sequence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etape de bienvenue",
                "verbose_name_plural": "Etapes de bienvenue",
                "ordering": ["sequence", "order"],
            },
        ),
        migrations.CreateModel(
            name="MemberAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Obtenu le"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_achievements",
                        to="onboarding.achievement",
                        verbose_name="Accomplissement",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accomplissement membre",
                "verbose_name_plural": "Accomplissements membre",
                "ordering": ["-earned_at"],
                "unique_together": {("member", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="DocumentSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "signature_text",
                    models.CharField(
                        max_length=200, verbose_name="Signature (nom complet)"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Signe le"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_signatures",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="onboarding.onboardingdocument",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature de document",
                "verbose_name_plural": "Signatures de documents",
                "ordering": ["-signed_at"],
                "unique_together": {("document", "member")},
            },
        ),
        migrations.CreateModel(
            name="OnboardingFormResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Valeur")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/form_responses/%Y/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="onboarding.onboardingformfield",
                        verbose_name="Champ",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_responses",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reponse au formulaire",
                "verbose_name_plural": "Reponses au formulaire",
                "unique_together": {("member", "field")},
            },
        ),
        migrations.CreateModel(
            name="WelcomeProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Etape courante"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Debut"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Termine le"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcome_progress",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_progress",
                        to="onboarding.welcomesequence",
                        verbose_name="Sequence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression bienvenue",
                "verbose_name_plural": "Progressions bienvenue",
                "unique_together": {("member", "sequence")},
            },
        ),
    ]
