# Generated by Django 5.0.6 on 2026-01-28 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu HTML')),
                ('content_plain', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('sending', "En cours d'envoi"), ('sent', 'Envoyée'), ('failed', 'Échec')], default='draft', max_length=20, verbose_name='Statut')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Planifiée pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('send_to_all', models.BooleanField(default=True, verbose_name='Envoyer à tous')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinataires')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='Ouvertures')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_newsletters', to='members.member')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='newsletters', to='members.group', verbose_name='Groupes cibles')),
            ],
            options={
                'verbose_name': 'Infolettre',
                'verbose_name_plural': 'Infolettres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('birthday', 'Anniversaire'), ('event', "Rappel d'événement"), ('volunteer', 'Rappel de bénévolat'), ('help_request', 'Mise à jour de requête'), ('donation', 'Reçu de don'), ('general', 'Général')], default='general', max_length=50)),
                ('link', models.URLField(blank=True, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.member')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('email_newsletter', models.BooleanField(default=True)),
                ('email_events', models.BooleanField(default=True)),
                ('email_birthdays', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='members.member')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='NewsletterRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('email', models.EmailField(max_length=254, verbose_name='Courriel')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_newsletters', to='members.member')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communication.newsletter')),
            ],
            options={
                'verbose_name': 'Destinataire',
                'verbose_name_plural': 'Destinataires',
                'unique_together': {('newsletter', 'member')},
            },
        ),
    ]
