# Generated by Django 5.2.11 on 2026-02-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Durée prévue de la session en minutes",
                null=True,
                verbose_name="Durée (minutes)",
            ),
        ),
    ]
