# Generated by Django 5.2.11 on 2026-02-14 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("member_stats", "Statistiques des membres"),
                            ("donation_summary", "Sommaire des dons"),
                            ("event_attendance", "Presence aux evenements"),
                            ("volunteer_hours", "Heures de benevolat"),
                            ("help_requests", "Demandes d'aide"),
                            ("communication", "Communications"),
                            ("custom", "Personnalise"),
                        ],
                        max_length=30,
                        verbose_name="Type de rapport",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Frequence",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier envoi"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prochain envoi"
                    ),
                ),
                (
                    "filters_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Filtres (JSON)"
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom du template"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_schedules",
                        to="members.member",
                        verbose_name="Cree par",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_schedules",
                        to="members.member",
                        verbose_name="Destinataires",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport planifie",
                "verbose_name_plural": "Rapports planifies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("member_stats", "Statistiques des membres"),
                            ("donation_summary", "Sommaire des dons"),
                            ("event_attendance", "Presence aux evenements"),
                            ("volunteer_hours", "Heures de benevolat"),
                            ("help_requests", "Demandes d'aide"),
                            ("communication", "Communications"),
                            ("custom", "Personnalise"),
                        ],
                        max_length=30,
                        verbose_name="Type de rapport",
                    ),
                ),
                (
                    "filters_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Filtres (JSON)"
                    ),
                ),
                (
                    "columns_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Colonnes (JSON)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_saved_reports",
                        to="members.member",
                        verbose_name="Cree par",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_reports",
                        to="members.member",
                        verbose_name="Partage avec",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport sauvegarde",
                "verbose_name_plural": "Rapports sauvegardes",
                "ordering": ["-created_at"],
            },
        ),
    ]
