# Generated by Django 5.2.11 on 2026-02-06 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0002_alter_donationcampaign_image"),
        ("members", "0003_member_two_factor_deadline_member_two_factor_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlinePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="CAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("succeeded", "Réussi"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("tithe", "Dîme"),
                            ("offering", "Offrande générale"),
                            ("special", "Offrande spéciale"),
                            ("campaign", "Campagne"),
                            ("building", "Bâtiment"),
                            ("missions", "Missions"),
                            ("other", "Autre"),
                        ],
                        default="offering",
                        max_length=20,
                        verbose_name="Type de don",
                    ),
                ),
                (
                    "receipt_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email du reçu"
                    ),
                ),
                (
                    "stripe_receipt_url",
                    models.URLField(blank=True, verbose_name="URL du reçu Stripe"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payments",
                        to="donations.donationcampaign",
                        verbose_name="Campagne",
                    ),
                ),
                (
                    "donation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payment",
                        to="donations.donation",
                        verbose_name="Don lié",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_payments",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement en ligne",
                "verbose_name_plural": "Paiements en ligne",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Stripe Subscription ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="CAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Hebdomadaire"), ("monthly", "Mensuel")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("tithe", "Dîme"),
                            ("offering", "Offrande générale"),
                            ("special", "Offrande spéciale"),
                            ("campaign", "Campagne"),
                            ("building", "Bâtiment"),
                            ("missions", "Missions"),
                            ("other", "Autre"),
                        ],
                        default="tithe",
                        max_length=20,
                        verbose_name="Type de don",
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prochain paiement"
                    ),
                ),
                (
                    "is_active_subscription",
                    models.BooleanField(default=True, verbose_name="Abonnement actif"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Annulé le"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_donations",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Don récurrent",
                "verbose_name_plural": "Dons récurrents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Stripe Customer ID"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customer",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Stripe",
                "verbose_name_plural": "Clients Stripe",
            },
        ),
    ]
