# Generated by Django 5.2.11 on 2026-02-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helprequestcategory",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indique si cet enregistrement est actif",
                verbose_name="Actif",
            ),
        ),
    ]
