# Generated by Django 5.0.6 on 2026-01-28 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role_type', models.CharField(choices=[('worship', 'Louange'), ('hospitality', 'Accueil'), ('technical', 'Technique'), ('children', 'Enfants'), ('youth', 'Jeunesse'), ('admin', 'Administration'), ('outreach', 'Évangélisation'), ('other', 'Autre')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('min_volunteers', models.PositiveIntegerField(default=1, verbose_name='Min requis')),
                ('max_volunteers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max')),
                ('skills_required', models.TextField(blank=True, verbose_name='Compétences requises')),
            ],
            options={
                'verbose_name': 'Poste de bénévolat',
                'verbose_name_plural': 'Postes de bénévolat',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('confirmed', 'Confirmé'), ('declined', 'Refusé'), ('completed', 'Complété'), ('no_show', 'Absent')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_schedules', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_schedules', to='members.member')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='volunteers.volunteerposition')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('declined', 'Refusé')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, verbose_name='Raison')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='members.member')),
                ('swap_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_received', to='members.member')),
                ('original_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='volunteers.volunteerschedule')),
            ],
            options={
                'verbose_name': "Demande d'échange",
                'verbose_name_plural': "Demandes d'échange",
            },
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('frequency', models.CharField(choices=[('weekly', 'Chaque semaine'), ('biweekly', 'Aux deux semaines'), ('monthly', 'Une fois par mois'), ('occasional', 'Occasionnellement')], default='monthly', max_length=20, verbose_name='Fréquence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_availability', to='members.member')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_volunteers', to='volunteers.volunteerposition')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'unique_together': {('member', 'position')},
            },
        ),
    ]
