# Generated by Django 5.2.11 on 2026-02-07 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_default_departments"),
        ("volunteers", "0002_volunteerschedule_reminder_1day_sent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedAbsence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("reason", models.TextField(blank=True, verbose_name="Raison")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_absences",
                        to="members.member",
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_absences",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absence prévue",
                "verbose_name_plural": "Absences prévues",
                "ordering": ["-start_date"],
            },
        ),
    ]
