# Generated by Django 5.0.6 on 2026-01-28 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequestCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=100)),
                ('name_fr', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Help Request Category',
                'verbose_name_plural': 'Help Request Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_progress', 'En cours'), ('resolved', 'Résolue'), ('closed', 'Fermée')], default='new', max_length=20)),
                ('is_confidential', models.BooleanField(default=False, help_text='Only visible to pastors and admins')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_help_requests', to='members.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='members.member')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='help_requests.helprequestcategory')),
            ],
            options={
                'verbose_name': 'Help Request',
                'verbose_name_plural': 'Help Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet enregistrement est actif', verbose_name='Actif')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal staff-only note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_request_comments', to='members.member')),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='help_requests.helprequest')),
            ],
            options={
                'verbose_name': 'Help Request Comment',
                'verbose_name_plural': 'Help Request Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
