# Generated by Django 5.2.11 on 2026-02-14 05:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_requests", "0002_alter_helprequestcategory_is_active"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenevolenceFund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom du fonds")),
                (
                    "total_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Solde total",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Fonds de bienfaisance",
                "verbose_name_plural": "Fonds de bienfaisance",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CrisisProtocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "protocol_type",
                    models.CharField(
                        help_text="Ex: décès, hospitalisation, catastrophe naturelle",
                        max_length=50,
                        verbose_name="Type de protocole",
                    ),
                ),
                (
                    "steps_json",
                    models.JSONField(
                        default=list,
                        help_text="Liste des étapes du protocole en JSON",
                        verbose_name="Étapes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocole de crise",
                "verbose_name_plural": "Protocoles de crise",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CrisisResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "contact_info",
                    models.TextField(blank=True, verbose_name="Coordonnées"),
                ),
                ("url", models.URLField(blank=True, verbose_name="Lien")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ex: soutien au deuil, ressources communautaires",
                        max_length=100,
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressource de crise",
                "verbose_name_plural": "Ressources de crise",
                "ordering": ["category", "title"],
            },
        ),
        migrations.AlterModelOptions(
            name="helprequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Demande d'aide",
                "verbose_name_plural": "Demandes d'aide",
            },
        ),
        migrations.AlterModelOptions(
            name="helprequestcategory",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Catégorie de demande",
                "verbose_name_plural": "Catégories de demandes",
            },
        ),
        migrations.AlterModelOptions(
            name="helprequestcomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
            },
        ),
        migrations.CreateModel(
            name="BenevolenceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant demandé"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Raison")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Soumise"),
                            ("reviewing", "En révision"),
                            ("approved", "Approuvée"),
                            ("denied", "Refusée"),
                            ("disbursed", "Déboursée"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "amount_granted",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant accordé",
                    ),
                ),
                (
                    "disbursed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de versement"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="benevolence_approvals",
                        to="members.member",
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="help_requests.benevolencefund",
                        verbose_name="Fonds",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benevolence_requests",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de bienfaisance",
                "verbose_name_plural": "Demandes de bienfaisance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de l'équipe"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_care_teams",
                        to="members.member",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipe de soins",
                "verbose_name_plural": "Équipes de soins",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MealTrain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Raison")),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True, verbose_name="Restrictions alimentaires"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("completed", "Complété"),
                            ("cancelled", "Annulé"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_trains_received",
                        to="members.member",
                        verbose_name="Bénéficiaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Train de repas",
                "verbose_name_plural": "Trains de repas",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PastoralCare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "care_type",
                    models.CharField(
                        choices=[
                            ("hospital_visit", "Visite à l'hôpital"),
                            ("home_visit", "Visite à domicile"),
                            ("phone_call", "Appel téléphonique"),
                            ("counseling", "Counseling"),
                            ("prayer_meeting", "Rencontre de prière"),
                            ("other", "Autre"),
                        ],
                        default="home_visit",
                        max_length=30,
                        verbose_name="Type de soin",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de suivi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("follow_up", "Suivi"),
                            ("closed", "Fermé"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pastoral_care_assigned",
                        to="members.member",
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pastoral_care_created",
                        to="members.member",
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastoral_care_received",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soin pastoral",
                "verbose_name_plural": "Soins pastoraux",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Anonyme"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Visible sur le mur de prière",
                        verbose_name="Public",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("answered", "Exaucée"),
                            ("closed", "Fermée"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'exaucement"
                    ),
                ),
                (
                    "testimony",
                    models.TextField(
                        blank=True,
                        help_text="Témoignage lorsque la prière est exaucée",
                        verbose_name="Témoignage",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Les demandes anonymes doivent être approuvées",
                        verbose_name="Approuvée",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_requests",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de prière",
                "verbose_name_plural": "Demandes de prière",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'adhésion"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_team_memberships",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="help_requests.careteam",
                        verbose_name="Équipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre d'équipe de soins",
                "verbose_name_plural": "Membres d'équipe de soins",
                "ordering": ["joined_at"],
                "unique_together": {("team", "member")},
            },
        ),
        migrations.CreateModel(
            name="MealSignup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="Confirmé"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_signups",
                        to="members.member",
                        verbose_name="Volontaire",
                    ),
                ),
                (
                    "meal_train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="help_requests.mealtrain",
                        verbose_name="Train de repas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription repas",
                "verbose_name_plural": "Inscriptions repas",
                "ordering": ["date"],
                "unique_together": {("meal_train", "volunteer", "date")},
            },
        ),
    ]
