# Generated by Django 5.2.11 on 2026-02-07 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_alter_donationcampaign_image"),
        ("members", "0004_alter_member_membership_status_alter_member_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceDelegation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Accordé le"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Révoqué le"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "delegated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_delegations_granted",
                        to="members.member",
                        verbose_name="Délégué par",
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_delegations_received",
                        to="members.member",
                        verbose_name="Délégué à",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délégation financière",
                "verbose_name_plural": "Délégations financières",
                "ordering": ["-granted_at"],
            },
        ),
    ]
