# Generated by Django 5.2.11 on 2026-02-14 05:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_financedelegation"),
        ("members", "0007_customfield_group_lifecycle_stage_backgroundcheck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="currency",
            field=models.CharField(
                default="CAD",
                help_text="Code de devise ISO 4217",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.CreateModel(
            name="CryptoDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "crypto_type",
                    models.CharField(
                        choices=[
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("LTC", "Litecoin"),
                            ("USDC", "USD Coin"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Type de cryptomonnaie",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Adresse du portefeuille",
                    ),
                ),
                (
                    "amount_crypto",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=18,
                        verbose_name="Montant en cryptomonnaie",
                    ),
                ),
                (
                    "amount_cad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Valeur en CAD au moment de la donation",
                        max_digits=12,
                        verbose_name="Équivalent en CAD",
                    ),
                ),
                (
                    "coinbase_charge_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID de charge Coinbase"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("expired", "Expiré"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "donation",
                    models.OneToOneField(
                        blank=True,
                        help_text="Don créé une fois la transaction confirmée",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crypto_detail",
                        to="donations.donation",
                        verbose_name="Don lié",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crypto_donations",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Don en cryptomonnaie",
                "verbose_name_plural": "Dons en cryptomonnaie",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="imports/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En traitement"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, verbose_name="Journal d'erreurs"),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre total de lignes"
                    ),
                ),
                (
                    "imported_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre importé"
                    ),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre ignoré"
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_imports",
                        to="members.member",
                        verbose_name="Importé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import de dons",
                "verbose_name_plural": "Imports de dons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(verbose_name="Numéro de ligne"),
                ),
                (
                    "data_json",
                    models.JSONField(default=dict, verbose_name="Données brutes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("valid", "Valide"),
                            ("invalid", "Invalide"),
                            ("imported", "Importé"),
                            ("duplicate", "Doublon"),
                            ("skipped", "Ignoré"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_rows",
                        to="donations.donation",
                        verbose_name="Don créé",
                    ),
                ),
                (
                    "donation_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="donations.donationimport",
                        verbose_name="Import",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'import",
                "verbose_name_plural": "Lignes d'import",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="MatchingCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "matcher_name",
                    models.CharField(
                        help_text="Nom de la personne ou organisation qui jumelle les dons",
                        max_length=200,
                        verbose_name="Nom du donateur jumelé",
                    ),
                ),
                (
                    "match_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Ex: 1.00 = dollar pour dollar, 0.50 = 50 cents par dollar",
                        max_digits=5,
                        verbose_name="Ratio de jumelage",
                    ),
                ),
                (
                    "match_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant maximal que le donateur jumelé contribuera",
                        max_digits=12,
                        verbose_name="Plafond de jumelage",
                    ),
                ),
                (
                    "matched_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total jumelé à ce jour",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_campaigns",
                        to="donations.donationcampaign",
                        verbose_name="Campagne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne de jumelage",
                "verbose_name_plural": "Campagnes de jumelage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant promis"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Hebdomadaire"),
                            ("biweekly", "Aux deux semaines"),
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("annually", "Annuel"),
                            ("one_time", "Unique"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("completed", "Complété"),
                            ("cancelled", "Annulé"),
                            ("paused", "En pause"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pledges",
                        to="donations.donationcampaign",
                        verbose_name="Campagne",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledges",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement",
                "verbose_name_plural": "Engagements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PledgeFulfillment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant appliqué"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledge_fulfillments",
                        to="donations.donation",
                        verbose_name="Don",
                    ),
                ),
                (
                    "pledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillments",
                        to="donations.pledge",
                        verbose_name="Engagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réalisation d'engagement",
                "verbose_name_plural": "Réalisations d'engagement",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="GivingGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant cible"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giving_goals",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif de dons",
                "verbose_name_plural": "Objectifs de dons",
                "ordering": ["-year"],
                "unique_together": {("member", "year")},
            },
        ),
        migrations.CreateModel(
            name="GivingStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si cet enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                (
                    "period",
                    models.CharField(
                        choices=[("mid_year", "Mi-année"), ("annual", "Annuel")],
                        max_length=20,
                        verbose_name="Période",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="statements/%Y/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de génération"
                    ),
                ),
                (
                    "emailed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi par courriel"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="giving_statements",
                        to="members.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relevé de dons",
                "verbose_name_plural": "Relevés de dons",
                "ordering": ["-year", "-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "year"], name="donations_g_member__a9364f_idx"
                    ),
                    models.Index(
                        fields=["year", "period"], name="donations_g_year_30a148_idx"
                    ),
                ],
                "unique_together": {("member", "year", "period")},
            },
        ),
        migrations.AddIndex(
            model_name="pledge",
            index=models.Index(
                fields=["member", "status"], name="donations_p_member__a44b10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pledge",
            index=models.Index(
                fields=["campaign"], name="donations_p_campaig_8b11a2_idx"
            ),
        ),
    ]
